 public class HOUSEHOLD {
    public static void main(String[] args) {
        
        int familyMembers = 4;
        double waterConsumedLitres = 450.75;
        int houseNumber = 102;
        char waterUsageStatus = 'A'; 

        
        System.out.println("--- Household Water-Usage Details ---");
        System.out.println("House Number: " + houseNumber);
        System.out.println("Number of Family Members: " + familyMembers);
        System.out.println("Water Consumed: " + waterConsumedLitres + " litres");
        System.out.println("Water Usage Status: " + waterUsageStatus);
    }
}
